---
- name: installer mysql, changer le mot de passe de root, creer une base donnes et utilisateur sur la machine locale
  hosts: localhost
  become: yes
  vars_files:  vars
  tasks:

  - name: installer mysql
    apt:
      update_cache: yes
      name: 
      - mysql-server
      - python3-mysqldb 
  
  - name: lancer le service mysql
    service:
      name: mysql
      state: started
      enabled: yes 
    ignore_errors: yes  
  
  - name: changer le mot de passe de root avec le fichier .my.cnf
    template:
      src: .my.cnf
      dest: /root/.my.cnf
  
  - name: creer une bd
    mysql_db:
      name: base
      state: present
  
  - name: creer un utilisateur avec tous les priviliges sur la base de donnes base
    mysql_user:
      name: brahim
      password: "{{ pass }}" 
      priv: "base.*:ALL"
      state: present

